Исправление ошибок типизации
Раньше без этих параметров могло выдать довольно странную ошибку по типу:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/rv/programing/Python/my/tg_bots/SchoolBot/test.py", line 60, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/rv/programing/Python/my/tg_bots/SchoolBot/test.py", line 46, in main
    events = await client.events.get(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rv/programing/Python/my/tg_bots/SchoolBot/.venv/lib/python3.12/site-packages/schoolmospy/core/events_client.py", line 52, in get
    return await self.client.get(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rv/programing/Python/my/tg_bots/SchoolBot/.venv/lib/python3.12/site-packages/schoolmospy/core/basic_client.py", line 95, in get
    return await self._handle_response(resp, response_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rv/programing/Python/my/tg_bots/SchoolBot/.venv/lib/python3.12/site-packages/schoolmospy/core/basic_client.py", line 66, in _handle_response
    return response_model.model_validate(response.json())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rv/programing/Python/my/tg_bots/SchoolBot/.venv/lib/python3.12/site-packages/pydantic/main.py", line 716, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 7 validation errors for Events
response.0.room_name
  Field required [type=missing, input_value={'id': 94, 'title': 'Мо... 'Экономика'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
response.0.room_number
  Field required [type=missing, input_value={'id': 94, 'title': 'Мо... 'Экономика'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
response.0.subject_name
  Field required [type=missing, input_value={'id': 94, 'title': 'Мо... 'Экономика'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
response.0.health_status
  Field required [type=missing, input_value={'id': 94, 'title': 'Мо... 'Экономика'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
response.0.absence_reason_id
  Field required [type=missing, input_value={'id': 94, 'title': 'Мо... 'Экономика'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
response.0.nonattendance_reason_id
  Field required [type=missing, input_value={'id': 94, 'title': 'Мо... 'Экономика'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
response.0.is_missed_lesson
  Field required [type=missing, input_value={'id': 94, 'title': 'Мо... 'Экономика'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing